-- FEFO batch inventory, movement ledger, and checkout allocation RPC.
--
-- Run after:
--   - 19_transactional_checkout_rpc.sql
--
-- Purpose:
--   Add physical inventory batches, movement history, sale-to-batch allocation
--   records, stock-in/adjustment RPCs, and replace checkout stock deduction with
--   earliest-expiring-batch-first allocation.

begin;

do $$
begin
  if to_regprocedure('private.current_user_is_admin()') is null
     or to_regprocedure('private.current_user_is_active()') is null
     or to_regprocedure('private.current_user_branch_id()') is null
     or to_regclass('public.profiles') is null then
    raise exception
      'Run the auth rollout and role-policy scripts before 20_fefo_batch_inventory.sql.';
  end if;

  if to_regclass('public.products') is null
     or to_regclass('public.branches') is null
     or to_regclass('public.sales') is null
     or to_regclass('public.sale_items') is null then
    raise exception
      'Run the products, branches, sales, and sale_items schema before 20_fefo_batch_inventory.sql.';
  end if;
end
$$;

create table if not exists public.inventory_batches (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on update cascade on delete cascade,
  branch_id integer not null references public.branches (id) on update cascade on delete restrict,
  batch_code text,
  quantity_received integer not null default 0 check (quantity_received >= 0),
  quantity_on_hand integer not null default 0 check (quantity_on_hand >= 0),
  expiration_date date,
  stock_in_date date not null default current_date,
  source text not null default 'stock-in'
    check (source in ('stock-in', 'adjustment', 'opening-balance')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on update cascade on delete cascade,
  batch_id bigint references public.inventory_batches (id) on update cascade on delete set null,
  branch_id integer not null references public.branches (id) on update cascade on delete restrict,
  movement_type text not null
    check (movement_type in ('stock-in', 'sale', 'adjustment', 'correction', 'opening-balance')),
  quantity_delta integer not null,
  quantity_after integer not null default 0 check (quantity_after >= 0),
  sale_id bigint references public.sales (id) on update cascade on delete set null,
  sale_item_id bigint references public.sale_items (id) on update cascade on delete set null,
  reference text,
  notes text,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.sale_item_batch_allocations (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales (id) on update cascade on delete cascade,
  sale_item_id bigint not null references public.sale_items (id) on update cascade on delete cascade,
  product_id bigint not null references public.products (id) on update cascade on delete cascade,
  batch_id bigint not null references public.inventory_batches (id) on update cascade on delete restrict,
  branch_id integer not null references public.branches (id) on update cascade on delete restrict,
  quantity integer not null check (quantity > 0),
  expiration_date date,
  created_at timestamptz not null default now()
);

create index if not exists idx_inventory_batches_product_branch
  on public.inventory_batches (product_id, branch_id);

create index if not exists idx_inventory_batches_fefo_available
  on public.inventory_batches (branch_id, product_id, expiration_date, stock_in_date, id)
  where quantity_on_hand > 0;

create index if not exists idx_inventory_movements_product_created
  on public.inventory_movements (product_id, created_at desc);

create index if not exists idx_inventory_movements_batch_created
  on public.inventory_movements (batch_id, created_at desc);

create index if not exists idx_sale_item_batch_allocations_sale_item
  on public.sale_item_batch_allocations (sale_item_id);

create index if not exists idx_sale_item_batch_allocations_batch
  on public.sale_item_batch_allocations (batch_id);

create unique index if not exists ux_sale_item_batch_allocations_item_batch
  on public.sale_item_batch_allocations (sale_item_id, batch_id);

create or replace function public.set_inventory_batch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists set_inventory_batches_updated_at on public.inventory_batches;
create trigger set_inventory_batches_updated_at
  before update on public.inventory_batches
  for each row
  execute function public.set_inventory_batch_updated_at();

create or replace function private.resolve_product_branch_id(
  p_branch_id integer,
  p_branch_name text
)
returns integer
language sql
stable
set search_path = public, private
as $$
  select coalesce(
    p_branch_id,
    (
      select b.id
      from public.branches b
      where b.name = p_branch_name
      limit 1
    ),
    case
      when p_branch_name = 'Dollar' then 2
      when p_branch_name = 'Sta. Lucia' then 1
      else null
    end
  );
$$;

create or replace function private.recalculate_product_stock(
  p_product_id bigint
)
returns integer
language plpgsql
security definer
set search_path = public, private
as $$
declare
  next_stock_quantity integer := 0;
begin
  select coalesce(sum(quantity_on_hand), 0)::integer
  into next_stock_quantity
  from public.inventory_batches
  where product_id = p_product_id;

  update public.products
  set stock_quantity = next_stock_quantity
  where id = p_product_id;

  return next_stock_quantity;
end;
$$;

revoke all on function private.resolve_product_branch_id(integer, text) from public;
revoke all on function private.recalculate_product_stock(bigint) from public;
grant execute on function private.resolve_product_branch_id(integer, text) to authenticated;
grant execute on function private.recalculate_product_stock(bigint) to authenticated;

insert into public.inventory_batches (
  product_id,
  branch_id,
  batch_code,
  quantity_received,
  quantity_on_hand,
  expiration_date,
  stock_in_date,
  source,
  notes
)
select
  product_row.id,
  branch_scope.branch_id,
  'OPENING-' || product_row.id::text,
  greatest(coalesce(product_row.stock_quantity, 0), 0),
  greatest(coalesce(product_row.stock_quantity, 0), 0),
  product_row.expiration_date,
  current_date,
  'opening-balance',
  'Migrated from products.stock_quantity during FEFO batch rollout.'
from public.products product_row
cross join lateral (
  select private.resolve_product_branch_id(product_row.branch_id, product_row.branch) as branch_id
) branch_scope
where coalesce(product_row.stock_quantity, 0) > 0
  and branch_scope.branch_id is not null
  and not exists (
    select 1
    from public.inventory_batches existing_batch
    where existing_batch.product_id = product_row.id
  );

insert into public.inventory_movements (
  product_id,
  batch_id,
  branch_id,
  movement_type,
  quantity_delta,
  quantity_after,
  reference,
  notes
)
select
  batch.product_id,
  batch.id,
  batch.branch_id,
  'opening-balance',
  batch.quantity_received,
  batch.quantity_on_hand,
  batch.batch_code,
  batch.notes
from public.inventory_batches batch
where batch.source = 'opening-balance'
  and batch.quantity_received > 0
  and not exists (
    select 1
    from public.inventory_movements movement
    where movement.batch_id = batch.id
      and movement.movement_type = 'opening-balance'
  );

do $$
declare
  product_id_row record;
begin
  for product_id_row in
    select distinct product_id
    from public.inventory_batches
  loop
    perform private.recalculate_product_stock(product_id_row.product_id);
  end loop;
end
$$;

alter table public.inventory_batches enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.sale_item_batch_allocations enable row level security;

revoke all on public.inventory_batches from anon, authenticated;
revoke all on public.inventory_movements from anon, authenticated;
revoke all on public.sale_item_batch_allocations from anon, authenticated;

grant select on public.inventory_batches to authenticated;
grant select on public.inventory_movements to authenticated;
grant select on public.sale_item_batch_allocations to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists inventory_batches_select_admin on public.inventory_batches;
create policy inventory_batches_select_admin
  on public.inventory_batches
  for select
  to authenticated
  using (private.current_user_is_admin());

drop policy if exists inventory_batches_select_assigned on public.inventory_batches;
create policy inventory_batches_select_assigned
  on public.inventory_batches
  for select
  to authenticated
  using (
    private.current_user_is_active()
    and branch_id = private.current_user_branch_id()
  );

drop policy if exists inventory_movements_select_admin on public.inventory_movements;
create policy inventory_movements_select_admin
  on public.inventory_movements
  for select
  to authenticated
  using (private.current_user_is_admin());

drop policy if exists inventory_movements_select_assigned on public.inventory_movements;
create policy inventory_movements_select_assigned
  on public.inventory_movements
  for select
  to authenticated
  using (
    private.current_user_is_active()
    and branch_id = private.current_user_branch_id()
  );

drop policy if exists sale_item_batch_allocations_select_admin on public.sale_item_batch_allocations;
create policy sale_item_batch_allocations_select_admin
  on public.sale_item_batch_allocations
  for select
  to authenticated
  using (private.current_user_is_admin());

drop policy if exists sale_item_batch_allocations_select_assigned on public.sale_item_batch_allocations;
create policy sale_item_batch_allocations_select_assigned
  on public.sale_item_batch_allocations
  for select
  to authenticated
  using (
    private.current_user_is_active()
    and (
      branch_id = private.current_user_branch_id()
      or exists (
        select 1
        from public.sales sale_row
        where sale_row.id = sale_item_batch_allocations.sale_id
          and sale_row.cashier_id = auth.uid()::text
      )
    )
  );

create or replace function private.ensure_inventory_batch_user_scope(
  p_branch_id integer
)
returns void
language plpgsql
security definer
set search_path = public, private
as $$
declare
  current_user_id uuid := auth.uid();
  current_role_key text;
  current_branch_id integer;
  current_status text;
begin
  if coalesce(auth.role(), '') <> 'authenticated' or current_user_id is null then
    raise exception 'Only authenticated accounts can update inventory batches.'
      using errcode = '42501';
  end if;

  select role_key, branch_id, status
  into current_role_key, current_branch_id, current_status
  from public.profiles
  where id = current_user_id
  limit 1;

  if current_status is distinct from 'active' then
    raise exception 'Only active accounts can update inventory batches.'
      using errcode = '42501';
  end if;

  if coalesce(current_role_key, '') <> 'admin'
     and p_branch_id is distinct from current_branch_id then
    raise exception 'Employee accounts can only update inventory for their assigned branch.'
      using errcode = '42501';
  end if;
end;
$$;

revoke all on function private.ensure_inventory_batch_user_scope(integer) from public;
grant execute on function private.ensure_inventory_batch_user_scope(integer) to authenticated;

create or replace function private.stock_in_inventory_batch(
  p_product_id bigint,
  p_branch_id integer,
  p_quantity integer,
  p_expiration_date date,
  p_stock_in_date date default current_date,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  product_row public.products%rowtype;
  product_branch_id integer;
  created_batch public.inventory_batches%rowtype;
begin
  perform private.ensure_inventory_batch_user_scope(p_branch_id);

  if p_product_id is null or p_branch_id is null then
    raise exception 'Product and branch are required for stock-in.'
      using errcode = '22023';
  end if;

  if coalesce(p_quantity, 0) <= 0 then
    raise exception 'Stock-in quantity must be greater than zero.'
      using errcode = '22023';
  end if;

  if p_expiration_date is null then
    raise exception 'Stock-in requires an expiration date for FEFO tracking.'
      using errcode = '22023';
  end if;

  select *
  into product_row
  from public.products
  where id = p_product_id
  for update;

  if not found then
    raise exception 'The selected product is no longer available.'
      using errcode = '23503';
  end if;

  product_branch_id := private.resolve_product_branch_id(
    product_row.branch_id,
    product_row.branch
  );

  if product_branch_id is distinct from p_branch_id then
    raise exception 'The selected product belongs to a different branch.'
      using errcode = '42501';
  end if;

  if coalesce(product_row.is_active, true) is not true then
    raise exception 'Inactive products cannot receive stock.'
      using errcode = '23514';
  end if;

  insert into public.inventory_batches (
    product_id,
    branch_id,
    batch_code,
    quantity_received,
    quantity_on_hand,
    expiration_date,
    stock_in_date,
    source,
    notes
  )
  values (
    p_product_id,
    p_branch_id,
    'BATCH-' || p_product_id::text || '-' || to_char(now(), 'YYYYMMDDHH24MISSMS'),
    p_quantity,
    p_quantity,
    p_expiration_date,
    coalesce(p_stock_in_date, current_date),
    'stock-in',
    nullif(btrim(coalesce(p_notes, '')), '')
  )
  returning *
  into created_batch;

  insert into public.inventory_movements (
    product_id,
    batch_id,
    branch_id,
    movement_type,
    quantity_delta,
    quantity_after,
    reference,
    notes,
    created_by
  )
  values (
    p_product_id,
    created_batch.id,
    p_branch_id,
    'stock-in',
    p_quantity,
    p_quantity,
    created_batch.batch_code,
    created_batch.notes,
    auth.uid()
  );

  perform private.recalculate_product_stock(p_product_id);

  return jsonb_build_object(
    'ok', true,
    'batch', to_jsonb(created_batch)
  );
end;
$$;

create or replace function public.stock_in_inventory_batch(
  p_product_id bigint,
  p_branch_id integer,
  p_quantity integer,
  p_expiration_date date,
  p_stock_in_date date default current_date,
  p_notes text default null
)
returns jsonb
language sql
set search_path = public, private
as $$
  select private.stock_in_inventory_batch(
    p_product_id,
    p_branch_id,
    p_quantity,
    p_expiration_date,
    p_stock_in_date,
    p_notes
  );
$$;

revoke all on function private.stock_in_inventory_batch(bigint, integer, integer, date, date, text) from public;
revoke all on function public.stock_in_inventory_batch(bigint, integer, integer, date, date, text) from public;
grant execute on function private.stock_in_inventory_batch(bigint, integer, integer, date, date, text) to authenticated;
grant execute on function public.stock_in_inventory_batch(bigint, integer, integer, date, date, text) to authenticated;

create or replace function private.adjust_inventory_stock_count(
  p_product_id bigint,
  p_branch_id integer,
  p_target_quantity integer,
  p_expiration_date date default null,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  product_row public.products%rowtype;
  product_branch_id integer;
  current_quantity integer := 0;
  quantity_difference integer := 0;
  remaining_quantity integer := 0;
  adjusted_quantity integer := 0;
  batch_quantity_after integer := 0;
  batch_row public.inventory_batches%rowtype;
  created_batch public.inventory_batches%rowtype;
begin
  perform private.ensure_inventory_batch_user_scope(p_branch_id);

  if p_product_id is null or p_branch_id is null then
    raise exception 'Product and branch are required for stock adjustment.'
      using errcode = '22023';
  end if;

  if coalesce(p_target_quantity, -1) < 0 then
    raise exception 'Adjusted stock quantity cannot be negative.'
      using errcode = '22023';
  end if;

  select *
  into product_row
  from public.products
  where id = p_product_id
  for update;

  if not found then
    raise exception 'The selected product is no longer available.'
      using errcode = '23503';
  end if;

  product_branch_id := private.resolve_product_branch_id(
    product_row.branch_id,
    product_row.branch
  );

  if product_branch_id is distinct from p_branch_id then
    raise exception 'The selected product belongs to a different branch.'
      using errcode = '42501';
  end if;

  select coalesce(sum(quantity_on_hand), 0)::integer
  into current_quantity
  from public.inventory_batches
  where product_id = p_product_id
    and branch_id = p_branch_id;

  quantity_difference := p_target_quantity - current_quantity;

  if quantity_difference = 0 then
    return jsonb_build_object(
      'ok', true,
      'stock_quantity', current_quantity
    );
  end if;

  if quantity_difference > 0 then
    if p_expiration_date is null then
      raise exception 'Increasing adjusted stock requires an expiration date for the added batch.'
        using errcode = '22023';
    end if;

    insert into public.inventory_batches (
      product_id,
      branch_id,
      batch_code,
      quantity_received,
      quantity_on_hand,
      expiration_date,
      stock_in_date,
      source,
      notes
    )
    values (
      p_product_id,
      p_branch_id,
      'ADJ-' || p_product_id::text || '-' || to_char(now(), 'YYYYMMDDHH24MISSMS'),
      quantity_difference,
      quantity_difference,
      p_expiration_date,
      current_date,
      'adjustment',
      nullif(btrim(coalesce(p_notes, '')), '')
    )
    returning *
    into created_batch;

    insert into public.inventory_movements (
      product_id,
      batch_id,
      branch_id,
      movement_type,
      quantity_delta,
      quantity_after,
      reference,
      notes,
      created_by
    )
    values (
      p_product_id,
      created_batch.id,
      p_branch_id,
      'adjustment',
      quantity_difference,
      quantity_difference,
      created_batch.batch_code,
      created_batch.notes,
      auth.uid()
    );
  else
    remaining_quantity := abs(quantity_difference);

    for batch_row in
      select *
      from public.inventory_batches
      where product_id = p_product_id
        and branch_id = p_branch_id
        and quantity_on_hand > 0
      order by expiration_date desc nulls first, stock_in_date desc, id desc
      for update
    loop
      exit when remaining_quantity <= 0;

      adjusted_quantity := least(remaining_quantity, batch_row.quantity_on_hand);

      update public.inventory_batches
      set quantity_on_hand = quantity_on_hand - adjusted_quantity
      where id = batch_row.id
      returning quantity_on_hand
      into batch_quantity_after;

      insert into public.inventory_movements (
        product_id,
        batch_id,
        branch_id,
        movement_type,
        quantity_delta,
        quantity_after,
        reference,
        notes,
        created_by
      )
      values (
        p_product_id,
        batch_row.id,
        p_branch_id,
        'adjustment',
        -adjusted_quantity,
        batch_quantity_after,
        batch_row.batch_code,
        nullif(btrim(coalesce(p_notes, '')), ''),
        auth.uid()
      );

      remaining_quantity := remaining_quantity - adjusted_quantity;
    end loop;

    if remaining_quantity > 0 then
      raise exception 'Adjusted stock is lower than available batch stock but could not be allocated.'
        using errcode = '23514';
    end if;
  end if;

  return jsonb_build_object(
    'ok', true,
    'stock_quantity', private.recalculate_product_stock(p_product_id)
  );
end;
$$;

create or replace function public.adjust_inventory_stock_count(
  p_product_id bigint,
  p_branch_id integer,
  p_target_quantity integer,
  p_expiration_date date default null,
  p_notes text default null
)
returns jsonb
language sql
set search_path = public, private
as $$
  select private.adjust_inventory_stock_count(
    p_product_id,
    p_branch_id,
    p_target_quantity,
    p_expiration_date,
    p_notes
  );
$$;

revoke all on function private.adjust_inventory_stock_count(bigint, integer, integer, date, text) from public;
revoke all on function public.adjust_inventory_stock_count(bigint, integer, integer, date, text) from public;
grant execute on function private.adjust_inventory_stock_count(bigint, integer, integer, date, text) to authenticated;
grant execute on function public.adjust_inventory_stock_count(bigint, integer, integer, date, text) to authenticated;

create or replace function private.create_checkout_sale(
  p_sale jsonb,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  current_user_id uuid := auth.uid();
  current_role_key text;
  current_branch_id integer;
  current_status text;
  sale_branch_id integer;
  sale_branch_name text;
  created_sale public.sales%rowtype;
  created_items jsonb := '[]'::jsonb;
  created_allocations jsonb := '[]'::jsonb;
  invalid_item_count integer := 0;
  mismatched_line_total_count integer := 0;
  expected_product_count integer := 0;
  locked_product_count integer := 0;
  product_row record;
  product_branch_id integer;
  product_available_quantity integer := 0;
  sale_payment_method text;
  sale_subtotal numeric := 0;
  sale_discount numeric := 0;
  sale_total_amount numeric := 0;
  sale_cash_received numeric := 0;
  sale_change_amount numeric := 0;
  calculated_product_subtotal numeric := 0;
  calculated_line_total numeric := 0;
  calculated_total_amount numeric := 0;
  sale_item_row public.sale_items%rowtype;
  batch_row public.inventory_batches%rowtype;
  allocation_row public.sale_item_batch_allocations%rowtype;
  remaining_quantity integer := 0;
  allocated_quantity integer := 0;
  batch_quantity_after integer := 0;
begin
  if coalesce(auth.role(), '') <> 'authenticated' or current_user_id is null then
    raise exception 'Only authenticated accounts can complete checkout.'
      using errcode = '42501';
  end if;

  select
    role_key,
    branch_id,
    status
  into
    current_role_key,
    current_branch_id,
    current_status
  from public.profiles
  where id = current_user_id
  limit 1;

  if current_status is distinct from 'active' then
    raise exception 'Only active accounts can complete checkout.'
      using errcode = '42501';
  end if;

  if jsonb_typeof(p_sale) is distinct from 'object' then
    raise exception 'Checkout sale payload must be a JSON object.'
      using errcode = '22023';
  end if;

  if jsonb_typeof(p_items) is distinct from 'array' then
    raise exception 'Checkout items payload must be a JSON array.'
      using errcode = '22023';
  end if;

  if jsonb_array_length(p_items) = 0 then
    raise exception 'Checkout requires at least one line item.'
      using errcode = '22023';
  end if;

  if nullif(p_sale->>'cashier_id', '') is distinct from current_user_id::text then
    raise exception 'Checkout cashier must match the authenticated account.'
      using errcode = '42501';
  end if;

  sale_branch_id := nullif(p_sale->>'branch_id', '')::integer;

  if sale_branch_id is null then
    raise exception 'Checkout branch is required.'
      using errcode = '22023';
  end if;

  select name
  into sale_branch_name
  from public.branches
  where id = sale_branch_id
  limit 1;

  if sale_branch_name is null then
    raise exception 'Checkout branch is not available.'
      using errcode = '23503';
  end if;

  if coalesce(current_role_key, '') <> 'admin'
     and sale_branch_id is distinct from current_branch_id then
    raise exception 'Employee accounts can only complete checkout for their assigned branch.'
      using errcode = '42501';
  end if;

  sale_payment_method := lower(coalesce(nullif(p_sale->>'payment_method', ''), 'cash'));
  sale_subtotal := coalesce(nullif(p_sale->>'subtotal', '')::numeric, 0);
  sale_discount := coalesce(nullif(p_sale->>'discount', '')::numeric, 0);
  sale_total_amount := coalesce(nullif(p_sale->>'total_amount', '')::numeric, 0);
  sale_cash_received := coalesce(nullif(p_sale->>'cash_received', '')::numeric, 0);
  sale_change_amount := coalesce(nullif(p_sale->>'change_amount', '')::numeric, 0);

  if sale_payment_method <> 'cash' then
    raise exception 'Only cash checkout is currently supported.'
      using errcode = '22023';
  end if;

  if sale_subtotal < 0
     or sale_discount < 0
     or sale_total_amount < 0
     or sale_cash_received < 0
     or sale_change_amount < 0 then
    raise exception 'Checkout amounts cannot be negative.'
      using errcode = '22023';
  end if;

  with parsed_items as (
    select
      nullif(item->>'product_id', '')::bigint as product_id,
      nullif(item->>'item_name', '') as item_name,
      coalesce(nullif(item->>'quantity', '')::integer, 0) as quantity,
      coalesce(nullif(item->>'unit_price', '')::numeric, 0) as unit_price,
      coalesce(nullif(item->>'line_total', '')::numeric, 0) as line_total
    from jsonb_array_elements(p_items) as source(item)
  )
  select count(*)
  into invalid_item_count
  from parsed_items
  where item_name is null
     or quantity <= 0
     or unit_price < 0
     or line_total < 0;

  if invalid_item_count > 0 then
    raise exception 'Checkout contains invalid line items.'
      using errcode = '22023';
  end if;

  with parsed_items as (
    select
      nullif(item->>'product_id', '')::bigint as product_id,
      coalesce(nullif(item->>'quantity', '')::integer, 0) as quantity,
      coalesce(nullif(item->>'unit_price', '')::numeric, 0) as unit_price,
      coalesce(nullif(item->>'line_total', '')::numeric, 0) as line_total
    from jsonb_array_elements(p_items) as source(item)
  )
  select
    coalesce(sum(case when product_id is not null then line_total else 0 end), 0),
    coalesce(sum(line_total), 0),
    count(*) filter (
      where round(line_total, 2) <> round(quantity * unit_price, 2)
    )
  into
    calculated_product_subtotal,
    calculated_line_total,
    mismatched_line_total_count
  from parsed_items;

  calculated_total_amount := greatest(0, calculated_line_total - sale_discount);

  if mismatched_line_total_count > 0 then
    raise exception 'Checkout line totals must match quantity and unit price.'
      using errcode = '22023';
  end if;

  if round(sale_subtotal, 2) <> round(calculated_product_subtotal, 2) then
    raise exception 'Checkout subtotal does not match product line items.'
      using errcode = '22023';
  end if;

  if sale_discount > calculated_product_subtotal then
    raise exception 'Checkout discount cannot be greater than the product subtotal.'
      using errcode = '22023';
  end if;

  if round(sale_total_amount, 2) <> round(calculated_total_amount, 2) then
    raise exception 'Checkout total does not match line items and discount.'
      using errcode = '22023';
  end if;

  if sale_cash_received < sale_total_amount then
    raise exception 'Cash received must be equal to or greater than total amount.'
      using errcode = '22023';
  end if;

  if round(sale_change_amount, 2) <> round(sale_cash_received - sale_total_amount, 2) then
    raise exception 'Checkout change does not match cash received and total amount.'
      using errcode = '22023';
  end if;

  with parsed_items as (
    select
      nullif(item->>'product_id', '')::bigint as product_id,
      coalesce(nullif(item->>'quantity', '')::integer, 0) as quantity
    from jsonb_array_elements(p_items) as source(item)
  ),
  product_quantities as (
    select
      product_id,
      sum(quantity)::integer as total_quantity
    from parsed_items
    where product_id is not null
    group by product_id
  )
  select count(*)
  into expected_product_count
  from product_quantities;

  for product_row in
    with parsed_items as (
      select
        nullif(item->>'product_id', '')::bigint as product_id,
        coalesce(nullif(item->>'quantity', '')::integer, 0) as quantity
      from jsonb_array_elements(p_items) as source(item)
    ),
    product_quantities as (
      select
        product_id,
        sum(quantity)::integer as total_quantity
      from parsed_items
      where product_id is not null
      group by product_id
    )
    select
      product.id,
      product.branch_id,
      product.branch,
      product.product_name,
      product.stock_quantity,
      product.is_active,
      product_quantities.total_quantity
    from product_quantities
    join public.products product
      on product.id = product_quantities.product_id
    order by product.id
    for update of product
  loop
    locked_product_count := locked_product_count + 1;
    product_branch_id := private.resolve_product_branch_id(
      product_row.branch_id,
      product_row.branch
    );

    if coalesce(product_row.is_active, true) is not true then
      raise exception '% is not available for checkout.', product_row.product_name
        using errcode = '23514';
    end if;

    if product_branch_id is null
       or product_branch_id is distinct from sale_branch_id then
      raise exception '% belongs to a different branch.', product_row.product_name
        using errcode = '42501';
    end if;

    select coalesce(sum(quantity_on_hand), 0)::integer
    into product_available_quantity
    from public.inventory_batches
    where product_id = product_row.id
      and branch_id = sale_branch_id
      and quantity_on_hand > 0;

    if product_row.total_quantity > product_available_quantity then
      raise exception '% only has % item(s) available in FEFO batches.',
        product_row.product_name,
        product_available_quantity
        using errcode = '23514';
    end if;
  end loop;

  if locked_product_count <> expected_product_count then
    raise exception 'One or more checkout items are no longer available.'
      using errcode = '23503';
  end if;

  insert into public.sales (
    cashier_id,
    cashier_name,
    branch_id,
    branch_name,
    payment_method,
    subtotal,
    discount,
    total_amount,
    cash_received,
    change_amount,
    submitted_at,
    notes
  )
  values (
    current_user_id::text,
    nullif(p_sale->>'cashier_name', ''),
    sale_branch_id,
    sale_branch_name,
    sale_payment_method,
    sale_subtotal,
    sale_discount,
    sale_total_amount,
    sale_cash_received,
    sale_change_amount,
    coalesce(nullif(p_sale->>'submitted_at', '')::timestamptz, now()),
    nullif(p_sale->>'notes', '')
  )
  returning *
  into created_sale;

  with parsed_items as (
    select
      ordinality,
      nullif(item->>'product_id', '')::bigint as product_id,
      nullif(item->>'inventory_item_id', '')::bigint as inventory_item_id,
      nullif(item->>'item_name', '') as item_name,
      coalesce(nullif(item->>'quantity', '')::integer, 0) as quantity,
      coalesce(nullif(item->>'unit_price', '')::numeric, 0) as unit_price,
      coalesce(nullif(item->>'line_total', '')::numeric, 0) as line_total
    from jsonb_array_elements(p_items) with ordinality as source(item, ordinality)
  )
  insert into public.sale_items (
    sale_id,
    product_id,
    inventory_item_id,
    item_name,
    quantity,
    unit_price,
    line_total
  )
  select
    created_sale.id,
    product_id,
    coalesce(inventory_item_id, product_id),
    item_name,
    quantity,
    unit_price,
    line_total
  from parsed_items
  order by ordinality;

  for sale_item_row in
    select *
    from public.sale_items
    where sale_id = created_sale.id
      and product_id is not null
    order by id
  loop
    remaining_quantity := sale_item_row.quantity;

    for batch_row in
      select *
      from public.inventory_batches
      where product_id = sale_item_row.product_id
        and branch_id = sale_branch_id
        and quantity_on_hand > 0
      order by expiration_date asc nulls last, stock_in_date asc, id asc
      for update
    loop
      exit when remaining_quantity <= 0;

      allocated_quantity := least(remaining_quantity, batch_row.quantity_on_hand);

      update public.inventory_batches
      set quantity_on_hand = quantity_on_hand - allocated_quantity
      where id = batch_row.id
      returning quantity_on_hand
      into batch_quantity_after;

      insert into public.sale_item_batch_allocations (
        sale_id,
        sale_item_id,
        product_id,
        batch_id,
        branch_id,
        quantity,
        expiration_date
      )
      values (
        created_sale.id,
        sale_item_row.id,
        sale_item_row.product_id,
        batch_row.id,
        sale_branch_id,
        allocated_quantity,
        batch_row.expiration_date
      )
      returning *
      into allocation_row;

      created_allocations := created_allocations || jsonb_build_array(to_jsonb(allocation_row));

      insert into public.inventory_movements (
        product_id,
        batch_id,
        branch_id,
        movement_type,
        quantity_delta,
        quantity_after,
        sale_id,
        sale_item_id,
        reference,
        created_by
      )
      values (
        sale_item_row.product_id,
        batch_row.id,
        sale_branch_id,
        'sale',
        -allocated_quantity,
        batch_quantity_after,
        created_sale.id,
        sale_item_row.id,
        created_sale.id::text,
        current_user_id
      );

      remaining_quantity := remaining_quantity - allocated_quantity;
    end loop;

    if remaining_quantity > 0 then
      raise exception '% could not be fully allocated to FEFO batches.',
        sale_item_row.item_name
        using errcode = '23514';
    end if;

    perform private.recalculate_product_stock(sale_item_row.product_id);
  end loop;

  select coalesce(jsonb_agg(to_jsonb(saved_item) order by saved_item.id), '[]'::jsonb)
  into created_items
  from public.sale_items saved_item
  where saved_item.sale_id = created_sale.id;

  return jsonb_build_object(
    'ok', true,
    'sale', to_jsonb(created_sale),
    'items', created_items,
    'allocations', created_allocations,
    'inventory_synced', true
  );
end;
$$;

revoke all on function private.create_checkout_sale(jsonb, jsonb) from public;
grant execute on function private.create_checkout_sale(jsonb, jsonb) to authenticated;

create or replace function public.create_checkout_sale(
  p_sale jsonb,
  p_items jsonb
)
returns jsonb
language sql
set search_path = public, private
as $$
  select private.create_checkout_sale(p_sale, p_items);
$$;

revoke all on function public.create_checkout_sale(jsonb, jsonb) from public;
grant execute on function public.create_checkout_sale(jsonb, jsonb) to authenticated;

commit;
